print ("Le agrego otra línea")
print ("Le agrego una linea mas")
print ("probando")
print ("sarasa")
print ("the pirulos")
print ("fuaa el diego")

archivo_nuevo = input("Cómo se hace para subir un nuevo archivo?: ")
print()
print ("# gracias! #")