print ("este es un archivo nuevo")
print ("agrego una linea nueva")
print ("agrego otra linea mas")
print ("practicando el programa git")
print ("seguimos jugando con git")
print ("Hola mundo")
print ("agrego otra linea")
print ("ok")
print ("agrego otra linea nueva")
print ("hola")
